### ISSUE TITLE
python library (Query Languages) compatile with titan 1.0 using dynamodb backend

### ISSUE THREAD

**Issue by MaiMal** [awslabs/dynamodb-titan-storage-backend#43]
On the tinkerpop3 website (http://tinkerpop.apache.org/), there are several python packages proposed as a query language to interact with titan 1.0. Can these be used for titan with a dynamodb backend and if so which one of them best to use?

**Comment by david-duverle** [comment]
I, too, am trying to get a dynamoDB backend working with Gremlin Python.

As far as I know, this requires Tinkerpop to have a GraphSON 2.0 serialiser, which is [only available starting with Tinkerpop 3.2.2](https://issues.apache.org/jira/browse/TINKERPOP-1274)…

The question then becomes whether it is possible to modify this package to use Tinkerpop 3.2…
I have tried editing the pom.xml file to change the version, but now running into dependency issues with groovy versions:
`Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 2.4.1 and you are trying to load version 2.4.7`

**Comment by amcp** [comment]
Titan 1.0.0 is built against TP 3.0.1, so effectively support for Gremlin Python is stuck in Titan. This package is built against Titan 1.0.0, so unless the build target is changed to something like [JanusGraph](https://github.com/JanusGraph/janusgraph), will also be stuck here.

Meanwhile, you could use the HTTP interface to Gremlin Server and interact with it by executing remote gremlin scripts.

**Comment by amcp** [comment]
This is not an issue with this plugin, and TP 3.2.X support is being tracked elsewhere (#60).
