### ISSUE TITLE
Creating tunnel from localhost to gremlin server timed out

### ISSUE THREAD

**Issue by Meng1980** [awslabs/dynamodb-titan-storage-backend#49]
Hi, I have been following this wiki for Launch DynamoDB Storage Backend for Titan: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.TitanDB.GremlinServerEC2.html

The stack has been deployed and I am stuck at Step 9. The error message I had is: ssh -o ServerAliveInterval=50 -nNT -L8182:localhost:8182 -i ${HOME}/.ec2/dynamodb-gremlin-server.pem.txt ec2-user@ec2-54-167-134-221.compute-1.amazonaws.com ssh: connect to host ec2-54-167-134-221.compute-1.amazonaws.com port 22: Operation timed out

I have the dynamodb-gremlin-server.pem SSH key created on AWS and downloaded locally, but I don't have the ${HOME}/.ec2/ dir locally. So I had to manually create the /.ec2 folder and copy the key into it. Not sure if I missed anything and if the time out error is related to this.

Please let me know if you have any suggestions. Thank you very much!!

**Comment by rpstreef** [comment]
In case people are wondering what the issue is here. The VPC stack is created with an ACL and a security group setting on Source 0.0.0.0/32 which means that access to the configured port 22 is still blocked. This needs to be changed to 0.0.0.0/0 and then connection can be established. Check both ACL of your VPC and the EC2 associated security group

**Comment by amcp** [comment]
You need to properly configure the access origin for SSH port 22. Otherwise, you will not be able to SSH. You could set it to the IP address of your own computer, or to the IP address/prefix of another EC2 host in case your IP is dynamic.
