### ISSUE TITLE
Cross-Region Replication with DynamoDB

### ISSUE THREAD

**Issue by leonhsu1** [awslabs/dynamodb-titan-storage-backend#71]
I'm trying to perform cross-region replication for Titan 1.0.0 back by DynamoDB with DynamoDB Streams + Lambda. I have a few questions regarding the tables that I'm trying to replicate.

1. Can I get a more detailed understanding of what the tables do? The only documentation that I could find about the titan tables in dynamoDB is on the [official documentation ](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.TitanDB.BestPractices.html). Should I be replicating all the tables that titan creates or only the ones that matter? (edgestore + graphindex).
2. I'm running into a problem where anytime Lambda writes to dynamoDB (through boto3 python), it will automatically encode binary data. Whenever I replicate from one region to another, it does a double encoding on the binary data. I've tried working around this solution by writing the encoded data as a string type, but Titan doesn't like that.

Has anyone else tried cross-region replication with Titan backed by dynamoDB?

Thanks for the help!

**Comment by amcp** [comment]
Thank you for the feedback.
1. `edgestore` stores all vertices, vertex properties and edges and their properties. `graphindex` is where all composite indexes of vertex and edge properties are stored. These indexes only support equality lookups. `systemlog` is Titan's system log and logs things like schema changes. `txlog` is the transaction log which you can optionally make Titan write to before committing work to the `edgestore`. `titan_ids` stores the id range leases for each UNIQUE_MACHINE_ID assigned to Titan servers as they start up. Finally, `system_properties` stores things like the graph schema (property types, multiplicity, indexes, etc).
2. Your automatic encoding issue seems related to a [similar issue raised in the aws-cli](https://github.com/aws/aws-cli/issues/1097) project. It seems like you will not be able to get around the encoding issue in Python/boto3 unless you do something hackish, so may I suggest you 1) raise an issue with the [boto3 sdk on GitHub](https://github.com/boto/boto3) and 2) write your lambda in Java using the Java SDK to unblock yourself?

**Comment by leonhsu1** [comment]
Thanks for reply! Writing the Lambda in Java unblocked the issue for myself.

Based on your explanation of the tables, what tables do you suggest that I replicate to ensure consistent reads across different regions? In other words, is there region specific data that is being stored in these tables? 

It seems like the tables that need to be replicated should only be `edgestore`, `graphindex`, and potentially `system_properties`. Let me know what is the best practice for replicating these tables.

Really appreciate the help!

**Comment by amcp** [comment]
Even if you just want read replicas in different regions, I would replicate all tables. Honestly, I think Titan server will create new tables with those names if they don't already exist in the region you are replicating to. This is not desirable in a replication scenario because I can imagine a situation where you only replicated graphindex and edgestore and Titan starts ISE/fatals because it can't find property type definitions in system_properties for the properties you indexed!!

The only tables that will see traffic in production are edgestore, graphindex and titan_ids, as long as your application does not make online schema changes. Therefore txlog and systemlog and system_properties are OK to provision at minimal levels in the replication target region.

**Comment by amcp** [comment]
resolving
