### ISSUE TITLE
Does this backend support parallelized bulk loading?

### ISSUE THREAD

**Issue by concretevitamin** [awslabs/dynamodb-titan-storage-backend#9]
Hi all,

Congrats on the launch & awesome work on this!

I've successfully built my application (bulk loading a graph) against this backend, and have it run against the local, in-memory DynamoDB. Now I'd like to switch to running against DynamoDB in the cloud, and perform bulk-loading from a single machine running Titan (in fact, an EC2 instance).

Here's what the code looks like:
```java
      // Each node file represents a distinct range of node IDs, and their properties
      for (String nodeFile : nodeFiles) {
          threads.add(new Thread(
              new NodeSplitLoader(g, config, nodeFile)));
      }
      for (Thread thread : threads) {
          thread.start();
      }

      // ....

      // Each thread creates its own BatchGraph over a single TitanGraph, and
      // handles one node file; inside each thread's run():
      BatchGraph bg = new BatchGraph(g, VertexIDType.NUMBER, 500000);
      for (each line) {
          // Do parsing to get nodeId and properties
          bg.addVertex(TitanId.toVertexId(nodeId), properties);
      }
      bg.commit()
```

The particular code is on Github [here](https://github.com/concretevitamin/titan-benchmark/blob/1fea275a7c6edfcee866a15b2695379072c75204/src/main/java/edu/berkeley/cs/ParLoadNode.java). Here's an example of what the node files look like:

```
// node file 1
0 prop1 prop2 ...
1 prop1 prop2 ...
...
99 prop1 prop2 ...

// node file 2
100 prop1 prop2 ...
...
```

Does the DynamoDB support such parallelized bulk loading?  Also, can I do the same parallelization with edges, after all the nodes are loaded?  The Titan version I'm using is 0.5.4.

**Comment by amcp** [comment]
The DynamoDB Storage Backend for Titan supports bulk loading through the batch-loading option and the Blueprints BatchGraph and through parallelized UpdateItem calls in the backend. You are using composite and mixed indexes in your benchmark.

Mixed:
https://github.com/concretevitamin/titan-benchmark/blob/1fea275a7c6edfcee866a15b2695379072c75204/src/main/java/edu/berkeley/cs/ParLoadNode.java#L104

Composite:
https://github.com/concretevitamin/titan-benchmark/blob/1fea275a7c6edfcee866a15b2695379072c75204/src/main/java/edu/berkeley/cs/ParLoadNode.java#L96

For each vertex/edge with an attribute that is indexed by a composite index, the backend will also make an UpdateItem call to the graphindex table. For the mixed indexes, these use indexing backends like Elasticsearch. The storage.buffer-size needs to be sufficient so that you write to graphindex and edgestore at the same time. Imagine a situation where you have a completely disconnected graph with only vertices with supplied ids. Further assume these vertices each have 3 composite-indexed properties. Because the default data model for the Storage Backend is the multiple-item model, each new vertex will result in at least 5 (1 hidden exists property, 1 property for the user supplied id, and three vertex property) UpdateItem calls on edgestore and 4 UpdateItem calls on graph index (3 for the properties, and one for the user supplied id). If storage.buffer-size is smaller than the number of UpdateItem calls (key-column mutation) in a tx.commit(), Titan will write to edgestore first, and then cycle through and write to graph index. If buffer-size is sufficiently large, we do shuffle the mutations as they are passed to the storage backend, so no further action is necessary to write to both the edgestore and graphindex at the same time. The same logic applies for edges

Now that you have an idea of how UpdateItem calls add up, then we can address the question of configuring the plugin for high load. As long as your vertex and edge properties are small in size, and if you use the multiple-item data model throughout, your items will generally be very small both in edgestore and graphindex. If you estimate a generous round trip time for writing small items at 20ms, that means one HTTP connection / thread (in the DynamoDB Storage Backend for Titan) can perform at least 50 key-column mutations per second. So it is good to set number of threads and HTTP connections consistently with storage.buffer-size (limits the maximum utilization of the DynamoDB Storage Backend for Titan's thread pool and HTTP connections). You will incur at least 1 WCU for each of these small items you write, so the provisioned throughput on your edgestore and graphindex tables needs to be in line with the spread of writes to the two tables, as outlined above.

It would be better to have one thread plopping new nodes and edges in the BatchGraph and let the Backend handle the parallelization. To reduce the back and forth to check and see if a vertex exists or not, would be better to add all the vertices and the vertex properties in the BatchGraph first, and then add the edges.

**Comment by amcp** [comment]
Lets use this one for reference and work through your bulk load in the second issue. Closing.
